CREATE USER 'root'@'%' IDENTIFIED BY 'opendocman66073888';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'opendocman'@'localhost' IDENTIFIED BY 'opendocman66073888';
GRANT ALL PRIVILEGES ON *.* TO 'opendocman'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'opendocman'@'%' IDENTIFIED BY 'opendocman66073888';
GRANT ALL PRIVILEGES ON *.* TO 'opendocman'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

DROP DATABASE IF EXISTS opendocman;
CREATE DATABASE IF NOT EXISTS opendocman DEFAULT CHARACTER SET UTF8 COLLATE utf8_general_ci;
USE `opendocman`;

SET FOREIGN_KEY_CHECKS=0;
